# Generated by Django 4.1.7 on 2023-06-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PetopiaApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetCategoryProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pet_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetopiaApp.petcategory",
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetopiaApp.productcategory",
                    ),
                ),
            ],
        ),
    ]
