# Generated by Django 4.1.7 on 2023-06-18 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PetopiaApp", "0002_petcategoryproductcategory"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartitem", name="cart",),
        migrations.RemoveField(model_name="cartitem", name="total_cost",),
        migrations.AddField(
            model_name="cartitem",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="test"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="date_ordered",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(name="User",),
    ]
