# Generated by Django 4.1.7 on 2023-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PetopiaApp", "0003_remove_cartitem_cart_remove_cartitem_total_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
