# Generated by Django 4.1.7 on 2023-06-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PetopiaApp", "0004_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="items",
            field=models.ManyToManyField(to="PetopiaApp.cartitem"),
        ),
    ]
