# Generated by Django 4.1.7 on 2023-06-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PetopiaApp", "0006_billingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="PetopiaApp.billingaddress",
            ),
        ),
    ]
