# Generated by Django 4.1.7 on 2023-06-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PetopiaApp", "0007_shoppingcart_billing_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingaddress", old_name="zim", new_name="zip",
        ),
    ]
