# Generated by Django 4.1.7 on 2023-06-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PetopiaApp", "0010_alter_product_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("food", "food"),
                    ("hygiene", "hygiene"),
                    ("toys", "toys"),
                    ("transport", "transport"),
                    ("other", "other"),
                ],
                max_length=10,
            ),
        ),
    ]
