# Generated by Django 4.1.7 on 2023-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PetopiaApp", "0011_alter_product_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="petcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/pet_images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("food", "food"),
                    ("hygiene", "hygiene"),
                    ("toys", "toys"),
                    ("transport", "transport"),
                ],
                max_length=10,
            ),
        ),
    ]
