# Generated by Django 4.1.7 on 2023-07-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PetopiaApp", "0013_productcategory_product_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="user",),
        migrations.RemoveField(model_name="product", name="category",),
        migrations.RemoveField(model_name="shoppingcart", name="billing_address",),
        migrations.RemoveField(model_name="shoppingcart", name="payment",),
        migrations.DeleteModel(name="BillingAddress",),
        migrations.DeleteModel(name="Payment",),
        migrations.DeleteModel(name="ProductCategory",),
    ]
